#!/usr/bin/python

import radio2
import sys
from getopt import getopt

usage = '''radio2-show show

Returns the URL of the page of the given
show (60s, 70s, at, jukebox, soul).'''

# Set the info from the command line argument.
if len(sys.argv[1:]) == 0:
  print usage
else:
  try:
    print 'http://bbc.co.uk/programmes/' + radio2.programCode(sys.argv[1])
  except AttributeError:
    print 'None'
