#!/usr/bin/python

import radio2
import sys
from getopt import getopt
import datetime

usage = '''radio2-rssitem [option] show length

options:
  -c:    use the episode's program code
  -h:    print this message

Without the -c option, it will generate a podcast RSS item for the most
recent episode of that show (70s, 60s, soul, at). If you use the -c option,
it can retrieve any episode using the given code.'''

# Parse the command line argument.
if len(sys.argv[1:]) < 2:
  print usage
  sys.exit()
else:
  optlist, args = getopt(sys.argv[1:], 'ch')
  if len(args) < 2:
    print usage
    sys.exit()
  if optlist:
    for o,a in optlist:
      if o == '-c':
        code = args[0]
        length = args[1]
      if o == '-h':
        print usage
        sys.exit()
  else:
    show = args[0]
    code = radio2.programCode(show)
    length = args[1]

# Construct the <item>.
item = radio2.rssitem(code, length)
if item:
  print item.encode('utf-8')
else:
  print "Not found"
