#!/usr/bin/python

import radio2
import sys
from getopt import getopt

usage = '''radio2-tracklist [option] [show]

options:
  -c code: use the show's program code rather than its name
  -h:      print this message

If you give the show name (60s, 70s, jukebox, soul), it will retrieve the tracklist
for the most recent episode of that show. If you use the -c option, it can retrieve
any episode.'''

# Parse the command line argument.
if len(sys.argv[1:]) == 0:
  print usage
  sys.exit()
else:
  optlist, args = getopt(sys.argv[1:], 'c:h')
  if len(args) > 0:
    try:
      code = radio2.programCode(args[0])
    except AttributeError:
      print 'None'
      sys.exit()
  for o,a in optlist:
    if o == '-c':
      code = a
    if o == '-h':
      print usage
      sys.exit()

try:
  print radio2.trackList(code).encode('utf-8')
except AttributeError:
  print 'None'
